# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: coordinator.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'coordinator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63oordinator.proto\x12\x0b\x63oordinator\"2\n\x0fRegisterRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\x0c\n\x04host\x18\x02 \x01(\t\"<\n\x10RegisterResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\x16\n\x0eheartbeat_secs\x18\x02 \x01(\x05\"2\n\x0bWorkRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\x10\n\x08max_docs\x18\x02 \x01(\x05\"@\n\tWorkBatch\x12\x10\n\x08\x62\x61tch_id\x18\x01 \x01(\t\x12!\n\x04\x64ocs\x18\x02 \x03(\x0b\x32\x13.coordinator.DocRef\"G\n\x06\x44ocRef\x12\x11\n\tsource_id\x18\x01 \x01(\t\x12\x14\n\x0c\x64ocument_url\x18\x02 \x01(\t\x12\x14\n\x0cworkspace_id\x18\x03 \x01(\t\"i\n\x10HeartbeatRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\x10\n\x08\x62\x61tch_id\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x11\n\tcompleted\x18\x04 \x01(\x05\x12\r\n\x05total\x18\x05 \x01(\x05\"\"\n\x0cHeartbeatAck\x12\x12\n\nkeep_going\x18\x01 \x01(\x08\"U\n\x0b\x42\x61tchResult\x12\x10\n\x08\x62\x61tch_id\x18\x01 \x01(\t\x12\x11\n\tworker_id\x18\x02 \x01(\t\x12\x11\n\tsucceeded\x18\x03 \x03(\t\x12\x0e\n\x06\x66\x61iled\x18\x04 \x03(\t\"!\n\rCompletionAck\x12\x10\n\x08received\x18\x01 \x01(\x08\x32\xa8\x02\n\x0b\x43oordinator\x12G\n\x08Register\x12\x1c.coordinator.RegisterRequest\x1a\x1d.coordinator.RegisterResponse\x12?\n\x0bRequestWork\x12\x18.coordinator.WorkRequest\x1a\x16.coordinator.WorkBatch\x12\x45\n\tHeartbeat\x12\x1d.coordinator.HeartbeatRequest\x1a\x19.coordinator.HeartbeatAck\x12H\n\x10ReportCompletion\x12\x18.coordinator.BatchResult\x1a\x1a.coordinator.CompletionAckb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'coordinator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERREQUEST']._serialized_start=34
  _globals['_REGISTERREQUEST']._serialized_end=84
  _globals['_REGISTERRESPONSE']._serialized_start=86
  _globals['_REGISTERRESPONSE']._serialized_end=146
  _globals['_WORKREQUEST']._serialized_start=148
  _globals['_WORKREQUEST']._serialized_end=198
  _globals['_WORKBATCH']._serialized_start=200
  _globals['_WORKBATCH']._serialized_end=264
  _globals['_DOCREF']._serialized_start=266
  _globals['_DOCREF']._serialized_end=337
  _globals['_HEARTBEATREQUEST']._serialized_start=339
  _globals['_HEARTBEATREQUEST']._serialized_end=444
  _globals['_HEARTBEATACK']._serialized_start=446
  _globals['_HEARTBEATACK']._serialized_end=480
  _globals['_BATCHRESULT']._serialized_start=482
  _globals['_BATCHRESULT']._serialized_end=567
  _globals['_COMPLETIONACK']._serialized_start=569
  _globals['_COMPLETIONACK']._serialized_end=602
  _globals['_COORDINATOR']._serialized_start=605
  _globals['_COORDINATOR']._serialized_end=901
# @@protoc_insertion_point(module_scope)
