# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import coordinator_pb2 as coordinator__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in coordinator_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CoordinatorStub:
    """Phase 3 — distributed worker pool.
    The coordinator hands out batches of document URLs to workers and tracks
    their liveness via heartbeats. If a worker stops heartbeating, its batch is
    re-enqueued and handed to another worker. Idempotent writes (Neo4j MERGE,
    ChromaDB upsert, conditional Postgres UPDATE) make a double-processed
    document harmless.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/coordinator.Coordinator/Register',
                request_serializer=coordinator__pb2.RegisterRequest.SerializeToString,
                response_deserializer=coordinator__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.RequestWork = channel.unary_unary(
                '/coordinator.Coordinator/RequestWork',
                request_serializer=coordinator__pb2.WorkRequest.SerializeToString,
                response_deserializer=coordinator__pb2.WorkBatch.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/coordinator.Coordinator/Heartbeat',
                request_serializer=coordinator__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=coordinator__pb2.HeartbeatAck.FromString,
                _registered_method=True)
        self.ReportCompletion = channel.unary_unary(
                '/coordinator.Coordinator/ReportCompletion',
                request_serializer=coordinator__pb2.BatchResult.SerializeToString,
                response_deserializer=coordinator__pb2.CompletionAck.FromString,
                _registered_method=True)


class CoordinatorServicer:
    """Phase 3 — distributed worker pool.
    The coordinator hands out batches of document URLs to workers and tracks
    their liveness via heartbeats. If a worker stops heartbeating, its batch is
    re-enqueued and handed to another worker. Idempotent writes (Neo4j MERGE,
    ChromaDB upsert, conditional Postgres UPDATE) make a double-processed
    document harmless.

    """

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestWork(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportCompletion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoordinatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=coordinator__pb2.RegisterRequest.FromString,
                    response_serializer=coordinator__pb2.RegisterResponse.SerializeToString,
            ),
            'RequestWork': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestWork,
                    request_deserializer=coordinator__pb2.WorkRequest.FromString,
                    response_serializer=coordinator__pb2.WorkBatch.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=coordinator__pb2.HeartbeatRequest.FromString,
                    response_serializer=coordinator__pb2.HeartbeatAck.SerializeToString,
            ),
            'ReportCompletion': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportCompletion,
                    request_deserializer=coordinator__pb2.BatchResult.FromString,
                    response_serializer=coordinator__pb2.CompletionAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'coordinator.Coordinator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('coordinator.Coordinator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Coordinator:
    """Phase 3 — distributed worker pool.
    The coordinator hands out batches of document URLs to workers and tracks
    their liveness via heartbeats. If a worker stops heartbeating, its batch is
    re-enqueued and handed to another worker. Idempotent writes (Neo4j MERGE,
    ChromaDB upsert, conditional Postgres UPDATE) make a double-processed
    document harmless.

    """

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coordinator.Coordinator/Register',
            coordinator__pb2.RegisterRequest.SerializeToString,
            coordinator__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestWork(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coordinator.Coordinator/RequestWork',
            coordinator__pb2.WorkRequest.SerializeToString,
            coordinator__pb2.WorkBatch.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coordinator.Coordinator/Heartbeat',
            coordinator__pb2.HeartbeatRequest.SerializeToString,
            coordinator__pb2.HeartbeatAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportCompletion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coordinator.Coordinator/ReportCompletion',
            coordinator__pb2.BatchResult.SerializeToString,
            coordinator__pb2.CompletionAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
